### ISSUE TITLE
Add -v option as alias to version

### ISSUE THREAD

**Issue by IanVS** [terminalvelocity/seeds.js#17]
It threw me for a bit of a loop when I tried `seeds -v` to check that installation was successful, and I got an ugly error message.  After checking the docs, I see that `seeds version` is the correct syntax, which was somewhat unexpected.  It would be nice to also support standard `-v` and `--version` arguments to display the installed version.

**Comment by jhliberty** [comment]
Can probably do this similarly to the convert-models command - during SeedsCLI instantiation, pass args to another file that parses aliases to actual commands and returns them back.
