### ISSUE TITLE
Deploy Process

### ISSUE THREAD

**Issue by jhliberty** [terminalvelocity/seeds.js#25]
Open to discussion on this

```
Push up Pod and PM2/Bootstrap iojs
Build ember app, cp to sails assets
Add repo and git push deploy
Spawn server on pm2 process
```

**Comment by IanVS** [comment]
What are your overall goals here?  A `seeds deploy` command which would do the above tasks?  Are you thinking about particular deployment targets?  Have you looked into [ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy)?  How simple or complicated do you want to make this?

**Comment by austinpray** [comment]
>Push up Pod and PM2/Bootstrap iojs
Build ember app, cp to sails assets

You should probably stop here. 

>Add repo and git push deploy
Spawn server on pm2 process

Seems way out of scope for this project.

**Comment by jamemackson** [comment]
with [ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy) nearing a pretty exciting (IMO) release I think the main deployment gap exists on the sails side.  I did see some niblets of code in sails master branch that look [suspiciously deployment related](https://github.com/balderdashy/sails/compare/v0.11.0...master#diff-80434ec026530d5b22044476b68d4791R16) but have no idea what state that is in nor when it is expected to land in a stable state.  Maybe we can evaluate that and make a plan from there.

**Comment by nahtnam** [comment]
Docker and Heroku are really the two most used methods out there, so IMO it should be the highest priority.

**Comment by austinpray** [comment]
>Docker and Heroku are really the two most used methods out there

Needs some sauce

**Comment by nahtnam** [comment]
?

**Comment by austinpray** [comment]
Provide a source for your claim, thanks.

**Comment by nahtnam** [comment]
None, other than personal experience. I just usually see people deploying to either heroku or use docker. And if docker works then people can set up other deploy methods fairly easily just by looking at the docker file...

**Comment by IanVS** [comment]
> Build ember app, cp to sails assets

Note, this can be done in one step with something like:

```bash
ember build --environment=production --output-path=../server/assets/
```

**Comment by jhliberty** [comment]
@nahtnam I deployed an example application to Heroku and found it relatively easy. https://seeds-blog.herokuapp.com 

A deployer command to Heroku shouldn't be too difficult. Like @IanVS said, it's essentially `ember build --environment=production -o ../api/assets` and then pushing the api folder to heroku.
