### ISSUE TITLE
Esperanto/Babelify/Transpile to ES5 (maybe)

### ISSUE THREAD

**Issue by jhliberty** [terminalvelocity/seeds.js#36]

**Comment by jhliberty** [comment]
Any thoughts on this?

**Comment by jhliberty** [comment]
the first thing that people seem to ask about is 

```
class SeedsCLI extends Cli {
^^^^^
SyntaxError: Unexpected reserved word
   at Module._compile (module.js:439:25)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at /usr/local/lib/node_modules/seeds/bin/seeds:13:11
   at /usr/local/lib/node_modules/seeds/node_modules/resolve/lib/async.js:46:14
   at process (/usr/local/lib/node_modules/seeds/node_modules/resolve/lib/async.js:173:43)
   at ondir (/usr/local/lib/node_modules/seeds/node_modules/resolve/lib/async.js:188:17)
```

Because they are not using io.js. With io.js and node merging back together, class should be implemented in node soon but I haven't been able to get an ETA or timeline from anyone on the node or io.js teams. 

Another benefit is access to certain things hidden behind the harmony flags that we can use before io.js/node implement them.

**Comment by jamemackson** [comment]
I would think for easy adoption for a greater number of people making it node compatible might be good.

**Comment by IanVS** [comment]
And even after they merge, not everyone will be using the latest version. A few stragglers will stay on 0.12 for whatever reason.

**Comment by jhliberty** [comment]
Those are both good reasons. I'll look into setting this up today - thanks for the feedback!

![](http://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)

**Comment by jhliberty** [comment]
#44
