### ISSUE TITLE
generate scaffold generates an error of attribute types on the models

### ISSUE THREAD

**Issue by HERRKIN** [terminalvelocity/seeds.js#4]
I did the scaffold command for user like in your example and when I tried registering a user I got an error saying that sails expected a number and I was sending 'age' (a string)

**Comment by jhliberty** [comment]
I included the file from sane to convert ember and sails model attributes. Wire the generator to invoke that and provide the right values for both sides.

https://github.com/terminalvelocity/seeds.js/blob/master/lib/helpers/convert-models.js
