### ISSUE TITLE
Use of const strict mode parsing dom error scaffolding

### ISSUE THREAD

**Issue by mikehence** [terminalvelocity/seeds.js#74]
I kept running into issues with Syntax errors when creating scaffolding. I fixed it by doing the following:

-installed NVM
-installed iojs
-NVM use iojs
-seeds new project name
-cd project name
-seeds s
-seeds g scaffold user firstName:string lastName:string email:string apiKey:string age:number subscribed:boolean verified:boolean

After that I did not get a blank screen anymore when visiting localhost:4200/users
All functionality is working but I have to use iojs. nodejs will not work due to strict mode

**Comment by jhliberty** [comment]
What version of node were using when you ran into the issue?

**Comment by pparke** [comment]
Just happened to me as well after installing seeds.js for the first time.  Node v0.12.5

**Comment by jhliberty** [comment]
I was able to reproduce this - It was from a related package and has been corrected with Ember CLI Seeds Scaffold pacakage: [80f8c4f30327](https://github.com/terminalvelocity/ember-cli-seeds-scaffold/commit/80f8c4f30327fff40301131290b2c0f39a7b950b)

**Comment by jhliberty** [comment]
`npm uninstall -g seeds`
`npm install -g seeds` 

and this should be corrected for node v0.12+. Support for v0.12 is going to be unsupported in a future release of seeds. I would recommend using Node v4 or greater.
